___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

6.3.0

In [3]:
import cufflinks as cf

In [4]:
# For Notebooks
init_notebook_mode(connected=True)

In [5]:
# For offline use
cf.go_offline()

### Fake Data

In [6]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [7]:
df.head()

          A         B         C         D
0 -0.389196  0.556950 -0.790387 -1.452389
1 -1.055976  0.438010 -1.242455  0.238896
2 -1.482942  2.391944  0.591417  1.679687
3  0.872905 -0.239684 -1.586509 -0.128648
4 -1.145054  0.720590 -1.721654  0.065014

In [8]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [9]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [10]:
df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)

ValueError:
    Invalid value of type 'builtins.str' received for the 'color' property of scatter.line
        Received value: 'rgba(226, 74, 51, np.float64(1.0))'

    The 'color' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color: see https://plotly.com/python/css-colors/ for a list

## Bar Plots

In [ ]:
df2.iplot(kind='bar',x='Category',y='Values')

In [ ]:
df.count().iplot(kind='bar')

## Boxplots

In [ ]:
df.iplot(kind='box')

## 3d Surface

In [ ]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

## Spread

In [ ]:
df[['A','B']].iplot(kind='spread')

## histogram

In [ ]:
df['A'].iplot(kind='hist',bins=25)

In [ ]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [ ]:
df.scatter_matrix()

# Great Job!